**IP1_JAG**

**Joey Gladys**

**Version 1.0**

**Spring 2022**

# a.

In [3]:
import numpy as np
arr1 = np.array([[10,20],[30,40]])
arr1

array([[10, 20],
       [30, 40]])

In [4]:
arr1**2

array([[ 100,  400],
       [ 900, 1600]])

In [5]:
arr1+100

array([[110, 120],
       [130, 140]])

In [6]:
arr1*5

array([[ 50, 100],
       [150, 200]])

In [7]:
np.sqrt(arr1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

# b.

In [8]:
arr2 = np.array([[3,6,9],[12,15,18],[21,24,27]])
arr3 = np.array([[11,12,13],[14,15,16],[17,18,19]])
arr2*arr3

array([[ 33,  72, 117],
       [168, 225, 288],
       [357, 432, 513]])

# c.

In [39]:
p1 = np.load('process1.npy')
p2 = np.load('process2.npy')
p3 = np.load('process3.npy')
p4 = np.load('process4.npy')
p5 = np.load('process5.npy')

arr4 = np.vstack((p1,p2,p3,p4,p5))
c1,c2,c3,c4,c5 = np.hsplit(arr4,5)

print(f'Column 1 mean = {c1.mean()}')
print(f'Column 2 mean = {c2.mean()}')
print(f'Column 3 mean = {c3.mean()}')
print(f'Column 4 mean = {c4.mean()}')
print(f'Column 5 mean = {c5.mean()}')

Column 1 mean = 72.0
Column 2 mean = 27.8
Column 3 mean = 45.6
Column 4 mean = 12.0
Column 5 mean = 47.8


In [40]:
arr4 = np.vstack((p1,p2,p3,p4,p5))
c1,c2,c3,c4,c5 = np.hsplit(arr4,5)
arr4

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)